using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibraryWebServiceConnect.Enums
{
    //ESTA CLASE FUNCIONA COMO DATOS "MAGICOS" ALGUNOS ESTAN FUERTEMENTE RELACIONADOS EN LA BASE DE DATOS CUYOS
    //VALORES NO SON CAMBIADOS POR ESTE SOFTWARE O STROREPROCEDURE, SON VALORES FIJOS

    public static class MagickInfo
    {
        public enum ROLES { ADMIN_PRINCIPAL = 1 ,STORE_ROL = 10, SUPERVISOR_ROL = 9}; //ESTOS SON ID EN LA BASE DE DATOS
        public enum STORE { ZERO = 81}; //ESTOS SON ID EN LA BASE DE DATOS   
        public enum SUPERVISOR { ADMINISTRADOR = 15}; //ESTOS SON ID EN LA BASE DE DATOS   
        public enum STATUS_REPORT { PROCESADO = 1, NO_PROCESADO = 2 }; //ESTOS SON ID EN LA BASE DE DATOS
        public enum STATUS { CIERRE_DE_MES = 5, AJUSTE_CON_EL_CIERRE = 16, S_E = 3 }; //ESTOS SON ID EN LA BASE DE DATOS
        public enum PERMISOS_INDEX { USUARIO, ROL, TIENDA, SUPERVISOR, 
            ESTATUS, REGISTRO_TIENDA, REGISTRO_SUPERVISOR, REPORTE_TIENDA, REPORTE_SUPERVISOR } //ESTE ES EL ORDEN DE LOS PERMISOS
        
        public enum USER_CONTROL_LIST_INDEX { INIT = 0, STORE_REPORT, SUPERVISOR_REPORT,STORE_REGISTER, SUPERVISOR_REGISTER, 
        STATUS, SUPERVISOR, STORES, USERS, ROLES};
    }
}
